### ISSUE TITLE
Generate files on a static folder

### ISSUE THREAD

**Issue by DenisAraujo68** [Ensepro/ensepro-answer-generator#2]
When we run ENSEPRO, it creates these files on the current folder:
- db.sqlite3
- elastic_search_step.json
- resultado_normalizado.json
- queries_renqueadas.json

Change the code to always create this files on the same fixed folder under the ENSEPRO's folder tree.

**Comment by alencarrh** [comment]
This issue was opened in the wrong place.
Moved to https://github.com/Ensepro/core/issues/1
